## Fundamental of tensorflow 

### Introduction to Tensors

In [2]:
# import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [3]:
# Create tensors
scalar = tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [4]:
# check the number of dimensions of a tensor
scalar.ndim

0

In [5]:
# create a vector
vector = tf.constant([1,2,3])
vector 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [6]:
# check dimensions of vector
vector.ndim

1

In [7]:
## create a matrix
matrix = tf.constant([[18,2],
                      [4,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[18,  2],
       [ 4,  5]], dtype=int32)>

In [8]:
# check the dimensions of matrix
matrix.ndim

2

In [9]:
matrix2 = tf.constant([[10., 7.],
                       [6., 8.],
                       [9., 3.]], dtype = tf.float16) # data type specification less precision than 32 so needs less memory to store
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 6.,  8.],
       [ 9.,  3.]], dtype=float16)>

In [10]:
# Creating a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor            

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
# dimensions
tensor.ndim

3

## Definitions
- Scalar -   a single number
- Vector -  a number with direction
- matrix -  a 2 dimension array of numbers
- a tensor -  an n-dimension array of numbers, vector is a 1-dim tensor

## Creating tensors with tf.Variable

In [12]:
# These a rea changeable tensors
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7] )
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Modifying elements of the changeable tensor
changeable_tensor[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

## Creating Random Tensors
- random tensors are often used to initialize weights. they contain random numbers and have arbitrary size

In [14]:
# Create two random tensors
random_1 = tf.random.Generator.from_seed(42) # random_seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

#Are the two distributions equal
random_1, random_2, random_2 == random_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffling the order of tensors
- if we have data that is ordered, such that the NN would learn about one element before the other.


In [15]:
not_shuffled = tf.constant([[7,10],
                            [6,5],
                            [4,2]])
not_shuffled.ndim

2

In [16]:
# shuffling  the not_shuffled
##. shuffles the "rows"
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  5],
       [ 7, 10],
       [ 4,  2]], dtype=int32)>

In [17]:
# using operational level seed >> we get random shuffles
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  2],
       [ 6,  5],
       [ 7, 10]], dtype=int32)>

In [18]:
## using global level set_seed >> we get same order
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  5],
       [ 4,  2],
       [ 7, 10]], dtype=int32)>

To make the shuffled data to reproduce the same order, use both global and operation level seeds
4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.


### Tensor of all ones

In [19]:
tf.ones([5,4])

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

### Tensor of all zeroes


In [20]:
tf.zeros([5,4])

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [21]:
tf.ones(shape=[5,4])

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

### Turning numpy arrays to Tf tensors
- Main difference is that tensors can be run on GPU, which is much faster

In [22]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [24]:
## changing the shape of the array
B = tf.constant(numpy_A, shape=(2,3,4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from Tensors
- shape - length(no. of elements) of each of the dimensions of a tensor
- Rank - The number of tensor dimnensions, scalar-0, vector-1,matrix-2, tensor-n
- Axis or dimension - a particular dimension of a tensor
- Size- total number of elements in a tensor

In [25]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

- The innermost dimension is 5(actual value counts),
- followed by 4 (number of arrays in an array)
- then 3(number of `array of arrays` in an a array) 
- then 2 (number of array of `arrays of arrays` in an a array)


In [26]:
"Shape:", rank_4_tensor.shape, "Dimensions:", rank_4_tensor.ndim, "Size:", tf.size(rank_4_tensor)

('Shape:',
 TensorShape([2, 3, 4, 5]),
 'Dimensions:',
 4,
 'Size:',
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [27]:
# Get various attributes of a tensor
print("Datattype of all elements:", rank_4_tensor.dtype)
print("Number of dimensions(Rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor as single value:", tf.size(rank_4_tensor).numpy())

Datattype of all elements: <dtype: 'float32'>
Number of dimensions(Rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor as single value: 120


In [28]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

### indexing tensors

In [29]:
# get first two elements
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [30]:
#Get first element from all dimensions except for the last one
rank_4_tensor[:1, :1, :1]
# same as. rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
# exclude the second last
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [32]:
rank_2_tensor = tf.constant([
                             [2,3],
                             [4,5]])
rank_2_tensor.ndim

2

In [33]:
# Get the last item of each of tow of our rank 2 tensor
# (Get all rows but last column)
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [34]:
# Add in extra dimension to rank 2 tensor
rank_3_tensor =  rank_2_tensor[..., tf.newaxis]
# ... imply all axis before last same as rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor.ndim

3

In [35]:
# Alternative way to tf.newaxis
another_rank_3_tensor_0 = tf.expand_dims(rank_2_tensor, axis=0)
# the new dim is at the beginning
another_rank_3_tensor_0

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [4, 5]]], dtype=int32)>

In [36]:
another_rank_3_tensor_1 = tf.expand_dims(rank_2_tensor, axis=1)
# now the new dim is the second axis
another_rank_3_tensor_1

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[2, 3]],

       [[4, 5]]], dtype=int32)>

In [37]:
another_rank_3_tensor_2 = tf.expand_dims(rank_2_tensor, axis=-1)
# now the new dim is the second axis
another_rank_3_tensor_2

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

### Arithmetic operations on Tensors
-- Element Wise

In [38]:
# add values to tensors
tensor = tf.constant([[10,7], [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [39]:
# mult
tensor * 12

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120,  84],
       [ 36,  48]], dtype=int32)>

In [40]:
# sub
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [41]:
# Division
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

- To optimize computation on GPU, use tensorflow operations

In [42]:
tf.multiply(tensor, 20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 140],
       [ 60,  80]], dtype=int32)>

In [43]:
tf.math.add(tensor, 50)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[60, 57],
       [53, 54]], dtype=int32)>

In [44]:
tf.math.subtract(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [-2, -1]], dtype=int32)>

 ### Matrix multiplication

In [45]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [46]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [47]:
## Multiply tensors with same Shape
X = tf.constant([[1,2], [2,3], [3,4]]) #3x2
Y = tf.constant([[4,5], [5,6], [6,7]]) # 3x2
try:
  tf.matmul(X,Y)
except Exception as e:
  print("Error in Multiplication:", e)

Error in Multiplication: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,2] 0 0 [Op:MatMul]


-  cannot multiply matrix with same shape
- The inner dimensions o the two matrices must match
- That is 3x2 can be multiplied by 2x3 because 2, 2 match

- Reshaping

In [48]:
Y_reshaped = tf.reshape(Y, shape=[2,3])
Y_reshaped

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 5],
       [6, 6, 7]], dtype=int32)>

In [49]:
tf.matmul(X, Y_reshaped)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16, 17, 19],
       [26, 28, 31],
       [36, 39, 43]], dtype=int32)>

In [50]:
X_reshaped = tf.reshape(X, shape=[2,3])
X_reshaped

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 2],
       [3, 3, 4]], dtype=int32)>

In [51]:
tf.matmul(X_reshaped, Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 31],
       [51, 61]], dtype=int32)>

- The result is the outter dimensions of the matrix 3x2 by 2x3 will result in a 3x3

- Transpose swaps the axis while reshape shuffles the element into the new shape

In [52]:
tf.transpose(X) , tf.reshape(X, shape= (2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [2, 3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 2],
        [3, 3, 4]], dtype=int32)>)

In [53]:
## multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 38],
       [47, 56]], dtype=int32)>

**The dot Product**
- Matrix multiplication is also called dot product
- It is done with
1.  `tf.matmul()`
2.  `tf.tensordot()`

In [54]:
tf.tensordot(X, tf.transpose(Y), axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14, 17, 20],
       [23, 28, 33],
       [32, 39, 46]], dtype=int32)>

In [55]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14, 17, 20],
       [23, 28, 33],
       [32, 39, 46]], dtype=int32)>

- Using tensordot with axis =  1 is equivalent to matmul

> Mostly we use transport with matmul



In [56]:
### Changing the datatype of a tensor

In [57]:
tf.__version__

'2.5.0'

In [58]:
# default datatype
B = tf.constant([1.5,2.5])
B.dtype

tf.float32

In [59]:
C = tf.constant([7,5])
C.dtype

tf.int32

In [60]:
# Change from float32 to float16 ( a reduced precision, for better memory)
B16 = tf.cast(B, dtype=tf.float16)
B16.dtype

tf.float16

### Aggregating Tensors

In [61]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [62]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [63]:
## Mean
tf.reduce_mean(tf.cast(D, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=-8.5>

In [64]:
## Create a random. tensor with values between 0 and 50
E = tf.constant(np.random.randint(0, 100, size=50))


In [65]:
## mean 
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=63>

In [66]:
## minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [67]:
## Maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [68]:
## Sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3174>

In [69]:
##Variance
try:
  tf.math.reduce_variance(E)
except Exception as e:
  print(e)

Input must be either real or complex


In [70]:
## Variance using tf
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=798.0>

In [71]:
# Variance using tensorflow probility
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=798>

In [72]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=28.25>

#### For Variance and Std to work with tf.math, values must be floats
- at which index is the maximum or minimum located

In [73]:
### Positional maximum and minimum
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F 

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [74]:
# find the position maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [75]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [76]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [77]:
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [78]:
# Find the position minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [79]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [80]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [81]:
assert F[tf.argmin(F)] == tf.reduce_min(F)

In [82]:
### Squeezing a tensor (Removing all single dimensions)
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [83]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [84]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [85]:
G2 =  tf.constant(tf.random.uniform(shape=[100]), shape=[1,1,1,2,50])
G2

<tf.Tensor: shape=(1, 1, 1, 2, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
          [0.20301068, 0.11448455, 0.35100245, 0.68227184, 0.18108869,
           0.8163481 , 0.65651655, 0.9258256 , 0.2391715 , 0.8365958 ,
           0.04765272, 0.8007157 , 0.8299267 , 0.14328372, 0.8616878 ,
           0.97072

In [86]:
tf.squeeze(G2)

<tf.Tensor: shape=(2, 50), dtype=float32, numpy=
array([[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       [0.20301068, 0.11448455, 0.35100245, 0.68227184, 0.18108869,
        0.8163481 , 0.65651655, 0.9258256 , 0.2391715 , 0.8365958 ,
        0.04765272, 0.8007157 , 0.8299267 , 0.14328372, 0.8616878 ,
        0.9707202 , 0.6779593 , 0.5641242 , 0.62537   , 0.8653159 

### One Hot encoding

In [87]:
# List of indices
L = [0,1,2,3]
# One hot encode the list
tf.one_hot(L, depth=4) # Depth defines the shape of the output matrix

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [88]:
# Specify custom values for one hot encoding
tf.one_hot(L, depth=3, on_value="Yes", off_value="No")

<tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b'Yes', b'No', b'No'],
       [b'No', b'Yes', b'No'],
       [b'No', b'No', b'Yes'],
       [b'No', b'No', b'No']], dtype=object)>

In [89]:
H = tf.range(10)
H

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [90]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

method needs float
- sqrt
- log

### TensorFlow and Numpy Array

In [91]:
J = tf.constant(np.array([3., 7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [92]:
np.array(J) , type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [93]:
J.numpy()[0]

3.0

In [94]:
### Default types of each
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3., 7., 10.])

# datatypes
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding Access to GPU 
- runtime  change in Runtime

In [95]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [96]:
!nvidia-smi

Thu Jul  1 12:42:58 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    57W / 149W |    124MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

- if GPU is running CUDA, Tensorflow will use it whenever possible

##Exercise

1. Creation

In [ ]:
escalar = tf.constant(1)
ematrix = tf.constant([2,3,4])
etensor = tf.constant([[2.,3.],[5.,6.]])
etensor

2. Rank Shape and Size

In [112]:
# Shape
escalar.shape, ematrix.shape, etensor.shape

(TensorShape([]), TensorShape([3]), TensorShape([2, 2]))

In [113]:
# Rank
escalar.ndim, ematrix.ndim, etensor.ndim

(0, 1, 2)

In [114]:
#Size
tf.size(escalar), tf.size(ematrix), tf.size(etensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

3. Random Tensor

In [119]:
tf.random.set_seed(42)
e_a1 = tf.random.uniform(shape = [5,300])
e_a2 = tf.random.uniform(shape = [5,300])
e_a2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
        0.9212563 ],
       [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
        0.51477313],
       [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
        0.9892651 ],
       [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
        0.8280058 ],
       [0.36690474, 0.9200133 , 0.9646884 , ..., 0.69012   , 0.7137332 ,
        0.2584542 ]], dtype=float32)>

4. Multiply 

In [122]:
mult = tf.matmul(e_a1, tf.transpose(e_a2))
mult

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33342 , 73.40498 , 77.15965 , 73.98369 , 80.90055 ],
       [75.146355, 68.80439 , 74.24303 , 71.8418  , 75.60204 ],
       [79.7594  , 75.64456 , 77.79758 , 74.74876 , 80.55982 ],
       [75.08526 , 69.06409 , 74.30775 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.134155]],
      dtype=float32)>

5. Multiply with dot

In [123]:
mult2 = tf.tensordot(e_a1, tf.transpose(e_a2), axes=1)
mult2

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33342 , 73.40498 , 77.15965 , 73.98369 , 80.90055 ],
       [75.146355, 68.80439 , 74.24303 , 71.8418  , 75.60204 ],
       [79.7594  , 75.64456 , 77.79758 , 74.74876 , 80.55982 ],
       [75.08526 , 69.06409 , 74.30775 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.134155]],
      dtype=float32)>

6. Random Tensor

In [129]:
random2 = tf.random.uniform(shape=[224,224,3])
random2

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ],
        ...,
        [0.98953485, 0.45382905, 0.2006687 ],
        [0.6295223 , 0.4937899 , 0.01816809],
        [0.95386636, 0.11542463, 0.85691285]],

       [[0.78435016, 0.7826872 , 0.87936425],
        [0.24906898, 0.3207239 , 0.10955775],
        [0.543224  , 0.7151396 , 0.40334642],
        ...,
        [0.2445668 , 0.01746976, 0.9036933 ],
        [0.02975535, 0.592268  , 0.9877522 ],
        [0.36701274, 0.33112562, 0.5638567 ]],

       [[0.15829337, 0.7288823 , 0.3366307 ],
        [0.70792687, 0.16910625, 0.9429966 ],
        [0.10120225, 0.5919596 , 0.8687303 ],
        ...,
        [0.28134012, 0.10011208, 0.37038183],
        [0.77874243, 0.05421627, 0.4664607 ],
        [0.2549187 , 0.7968637 , 0.83405185]],

       ...,

       [[0.32922816, 0.06343532, 0.23936498],
        [0.42

7 min max values

In [140]:
tf.reduce_max(random2[0]), tf.reduce_min(random2[0])

(<tf.Tensor: shape=(), dtype=float32, numpy=0.99829125>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0053213835>)

8. squeeze

In [142]:
tf.squeeze(tf.random.uniform(shape=[1,224,224,3])).shape

TensorShape([224, 224, 3])

9. Index of min

In [147]:
ts = tf.constant([2,3,3,4,5,5,6,1,456,7])
min_index = tf.argmin(ts)
min_index

<tf.Tensor: shape=(), dtype=int64, numpy=7>

10. One hot encoding

In [157]:
value, idx = tf.unique(ts)
value

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([  2,   3,   4,   5,   6,   1, 456,   7], dtype=int32)>

In [158]:
length = tf.size(value)
he = tf.one_hot(ts, depth=length)
he

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>